In [1]:
import numpy as np

## Array

In [4]:
#Create an array with specific data type
#Pass a list, nested list, tuple
np.array([1,2,3], dtype=np.uint)

array([1, 2, 3], dtype=uint32)

In [6]:
#Create an array with boolean
np.array([1,0,1,0], dtype=bool)

array([ True, False,  True, False])

In [7]:
#Create an array with specific range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Specify the range and how big the step is
np.arange(2,100, 5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [9]:
#Create an array in specific range with specific number of elements
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Matrix

#### Empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. 
On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [16]:
# Create an empty matrix
# Return a new array of given shape and type, without initializing entries
print(np.empty((3,3))); print(np.empty([3,3]))

[[0.11111111 0.22222222 0.33333333]
 [0.44444444 0.55555556 0.66666667]
 [0.77777778 0.88888889 1.        ]]
[[0.11111111 0.22222222 0.33333333]
 [0.44444444 0.55555556 0.66666667]
 [0.77777778 0.88888889 1.        ]]


In [17]:
#Create an array with 0 elements
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#Create the matrix filled with specified elements
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [20]:
#Create an identity matrix with dimension 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#Create a diagonal matrix with diagonal elements specified in the array x
x = [1,2,3]
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
#Create a matrix with random elements between 0 and 1
np.random.random((3,3))

array([[0.69500915, 0.77870072, 0.25456864],
       [0.71287762, 0.5661223 , 0.22814498],
       [0.70079229, 0.36475064, 0.34376336]])

In [23]:
#Create a matrix with random float elements with a specific range
np.random.normal(0, 10, (3,3))

array([[ -7.12333606,  -6.61855788,   8.75127031],
       [-12.7785456 ,  -7.83034193,   6.0475495 ],
       [  5.95369054, -17.47348244,  -1.53083473]])

In [24]:
#Create a matrix with random integer elements with a specific range
np.random.randint(0,10, (3,3))

array([[1, 5, 4],
       [9, 5, 4],
       [4, 5, 6]])

In [26]:
#Create the matrix with the same dimension but different elements
A = np.random.randint(0,10, (3,3))
print (A)

[[3 3 6]
 [3 4 7]
 [6 8 5]]


In [28]:
B = np.ones_like(A)
print (B)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Operations on matrices

In [29]:
A = np.array([[1, 1, 1], [2, 2, 2]], dtype= np.float64)
B = np.array([[1, 3, 4], [3, 2, 1]], dtype= np.float64)
print(A);print(B)

[[1. 1. 1.]
 [2. 2. 2.]]
[[1. 3. 4.]
 [3. 2. 1.]]


In [30]:
#Pointwise addition and multiplication
A + B

array([[2., 4., 5.],
       [5., 4., 3.]])

In [31]:
A * B

array([[1., 3., 4.],
       [6., 4., 2.]])

In [32]:
C = np.array([1,2,3], dtype = np.float64)
print(C)

[1. 2. 3.]


In [33]:
#Matrix multiplication
#Make sure the dimension of A is mxn and dimension of C is nxp
A@C

array([ 6., 12.])

In [34]:
# Matrix multiplication alternative
np.dot(A, C)

array([ 6., 12.])

In [35]:
#Find the transpose of a matrix
#Transpose: Columns become rows and rows become columns
A.T

array([[1., 2.],
       [1., 2.],
       [1., 2.]])

In [36]:
# reshape the array
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
#Return the sum along the diagonals of the array
np.trace(A)

3.0

In [38]:
# a.T * y (1xn * nx1)
a = np.arange(5)
b = np.arange(5)

In [39]:
#this returns a scaler
np.dot(a,b)

30

In [40]:
# a * y.T  (nx1 * 1*n)
#this returns a matrix nxn
np.outer(a,b)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [41]:
#Use boolean to return a specific row
A[[True, False],]

array([[1., 1., 1.]])

In [42]:
#Or column
A[:, [True, False, False]]

array([[1.],
       [2.]])

### Linear Algebra

In [44]:
#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
np.linalg.solve(a, b)

array([2., 3.])

In [45]:
#Compute the inverse of a matrix
np.linalg.pinv(A)

array([[0.06666667, 0.13333333],
       [0.06666667, 0.13333333],
       [0.06666667, 0.13333333]])

In [46]:
#Return matrix norm
np.linalg.norm(A)

3.872983346207417

In [48]:
#Single Value Decomposition
U, S, V = np.linalg.svd(A)
print(U); print(S); print(V)

[[-0.4472136   0.89442719]
 [-0.89442719 -0.4472136 ]]
[3.87298335e+00 1.46571787e-16]
[[-5.77350269e-01 -5.77350269e-01 -5.77350269e-01]
 [ 8.16496581e-01 -4.08248290e-01 -4.08248290e-01]
 [-6.99362418e-17 -7.07106781e-01  7.07106781e-01]]


In [50]:
A = np.arange(9).reshape(3,3)
#Find eigenvalues on square matrix
np.linalg.eig(A)

(array([ 1.33484692e+01, -1.34846923e+00, -1.26963291e-15]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

### Common Method for Data Science

In [51]:
#Flatten a matrix by row
A.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
#Flatten a matrix by column
A = A.flatten(order='F')

In [55]:
#Reshape the flattened matrix
A = A.reshape((3,3))
print(A)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [56]:
#Change the type of the elements
A.astype(np.float64) 

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.]])

In [57]:
#Create a copy of A
newA = np.copy(A)
newA

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [58]:
B = np.array([[1, 3],
             [4, 3],
             [2, 1]])

In [59]:
#Add the matrix B to columns of matrix A 
np.concatenate([A,B], axis = 1) 

array([[0, 3, 6, 1, 3],
       [1, 4, 7, 4, 3],
       [2, 5, 8, 2, 1]])

In [60]:
#Add the matrix B to rows of matrix A 
np.concatenate([A,B.reshape(2, 3)], axis = 0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [1, 3, 4],
       [3, 2, 1]])

In [61]:
#Create a copy of A with every entry in the matrix, the lowest is 0 and highest is 5
#The element that does not satisfy the condition will become the lowest or highest value
np.clip(A, 0.0, 5)

array([[0., 3., 5.],
       [1., 4., 5.],
       [2., 5., 5.]])

In [62]:
#Add the elements in the same row to create a new vector
np.sum(A, axis = 1)

array([ 9, 12, 15])

In [63]:
#Take the average the elements in the same row to create a new vector
np.average(A, axis = 1)

array([3., 4., 5.])

In [65]:
x = np.arange(10)
#Shuffle the elements in the array
np.random.shuffle(x)
x

array([2, 4, 5, 3, 6, 1, 9, 8, 7, 0])

In [66]:
#Or matrix
np.random.shuffle(A)
A

array([[2, 5, 8],
       [0, 3, 6],
       [1, 4, 7]])